#!/bin/bash

echo "Symfony version: ${SYMFONY_VERSION}"

if [ "${SYMFONY_VERSION}" = "2.0.*" ]; then
    echo "Using Symfony 2.0 requirements"
    rm composer.json
    cp Tests/composer20.json composer.json
fi

composer install --dev